package views;

import javax.swing.JLabel;
import javax.swing.JList;


public class formLista extends javax.swing.JFrame {

    public JList<String> getLblList() {
        return lblList;
    }

    public void setLblList(JList<String> lblList) {
        this.lblList = lblList;
    }
    
    public JLabel getLblFondoLista() {
        return lblFondoLista;
    }

    public void setLblFondoLista(JLabel lblFondoLista) {
        this.lblFondoLista = lblFondoLista;
    }

    public JLabel getLblCerrar() {
        return lblCerrar;
    }

    public void setLblCerrar(JLabel lblCerrar) {
        this.lblCerrar = lblCerrar;
    }

    public JLabel getLblOpcionesLista() {
        return lblOpcionesLista;
    }

    public void setLblOpcionesLista(JLabel lblOpcionesLista) {
        this.lblOpcionesLista = lblOpcionesLista;
    }

    public JLabel getLblPC() {
        return lblPC;
    }

    public void setLblPC(JLabel lblPC) {
        this.lblPC = lblPC;
    }

    public JLabel getLblTotal() {
        return lblTotal;
    }

    public void setLblTotal(JLabel lblTotal) {
        this.lblTotal = lblTotal;
    }

    
    
    
    
    public formLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblList = new javax.swing.JList<>();
        lblPC = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblOpcionesLista = new javax.swing.JLabel();
        lblFondoLista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTotal.setText("0 <-- Canciones");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(360, 110, 150, 30);

        lblList.setBackground(new java.awt.Color(153, 153, 153));
        lblList.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblList.setForeground(new java.awt.Color(102, 255, 255));
        lblList.setToolTipText("");
        lblList.setSelectionBackground(new java.awt.Color(102, 102, 255));
        jScrollPane1.setViewportView(lblList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 200, 400, 230);

        lblPC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblPC);
        lblPC.setBounds(30, 10, 120, 120);

        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblCerrar);
        lblCerrar.setBounds(770, 0, 60, 60);

        lblOpcionesLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lblOpcionesLista);
        lblOpcionesLista.setBounds(650, 20, 90, 30);

        lblFondoLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/INTERFAZMP3 2.png"))); // NOI18N
        getContentPane().add(lblFondoLista);
        lblFondoLista.setBounds(0, -10, 860, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblFondoLista;
    private javax.swing.JList<String> lblList;
    private javax.swing.JLabel lblOpcionesLista;
    private javax.swing.JLabel lblPC;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
